### ISSUE TITLE
The latest PX4 simulator handling the drone camera does not work on windows docker

### ISSUE THREAD

**Issue by Julien-Sahli** [Ph0tonic/SDP_Projet#117]

**Comment by JonasVautherin** [comment]
I assume it's about `px4-gazebo-headless`? What happens on Windows, and which docker is it?

**Comment by Julien-Sahli** [comment]
Yes, exactly. With Docker (not tested with Docker toolbox), the simulator does not connects with QGroundControl, nor the MavLink server (I guess it could be the IP like last time)

**Comment by JonasVautherin** [comment]
Can you show me how you run it (`docker run ...`)?

Didn't it use to work?

**Comment by Julien-Sahli** [comment]
I run it if the following command :
`docker run --rm -it -p 8554:8554 jonasvautherin/px4-gazebo-headless:latest`
and it won't connect.

If I do `docker run --rm -it --entrypoint bash jonasvautherin/px4-gazebo-headless:latest` then go in /root/Firmware,
` getent hosts` shows the following :
127.0.0.1       localhost
127.0.0.1       localhost ip6-localhost ip6-loopback
172.17.0.2      2c734c663c26
and `getent hosts host.docker.internal` shows
192.168.65.2    host.docker.internal

Maybe this can help

**Comment by JonasVautherin** [comment]
Didn't it use to work on that same computer? I'm asking because calling `:latest` doesn't mean it will update it. It may use the cache.

So to make sure you are using the latest image, maybe adding `--no-cache` to `docker run` may do it, otherwise just `docker rmi jonasvautherin/px4-gazebo-headless` to remove it because you run it again. I haven't tested them, maybe those commands are not exactly right, but that's the idea. 

Would you mind trying that and confirming that it still doesn't work? And tell me if it used to work on this computer (which would hint that there was a regression)? :blush:

**Comment by Julien-Sahli** [comment]
Edit : removing the local image of latest and downloading it again fixed the problem (the image I had locally was not the last one)
